# Generated by Django 3.1 on 2020-08-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrumsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drums_model', models.CharField(max_length=200, unique=True)),
                ('drums_brand', models.CharField(max_length=200)),
                ('drums_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DrumsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drums_store', models.CharField(max_length=200)),
                ('drums_units', models.IntegerField()),
                ('drums_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drums.drumsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DrumsCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drums_address', models.CharField(max_length=200, unique=True)),
                ('drums_cost', models.IntegerField()),
                ('drums_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drums.drumsmodel')),
                ('drums_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drums.drumsstore')),
            ],
        ),
    ]
