# Generated by Django 3.1 on 2020-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrumsSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drums_model', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
