# Generated by Django 3.1 on 2020-08-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.item')),
                ('drink_caffeine', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_calories',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
