# Generated by Django 3.1 on 2020-08-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200824_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='id',
            field=models.AutoField(auto_created=True, default='1234', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.item'),
        ),
    ]
