# Generated by Django 3.1 on 2020-08-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200824_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.item'),
        ),
    ]
