# Generated by Django 3.1 on 2020-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200824_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.item'),
        ),
    ]
