# Generated by Django 3.1 on 2020-08-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200824_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu_name',
            field=models.ForeignKey(on_delete=models.SET('Cocktail'), to='app1.menu'),
        ),
    ]
